Fix: Revert PDF links
hlxsites/accenture-newsroom pull request #154
Opened 2023-09-21 07:55 UTC by jjjaspher

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix https://github.com/hlxsites/accenture-newsroom/issues/133

- https://github.com/hlxsites/accenture-newsroom/issues/133https://github.com/hlxsites/accenture-newsroom/issues/133

Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory
- After: https://84836-PDF-Links--accenture-newsroom--hlxsites.hlx.page/news/2023/accenture-completes-acquisition-of-anser-advisory

2023-09-21 15:40 UTC, amol-anand approved these changes

2023-09-21 23:30 UTC, ravkiran commented
@jjjaspher I'm still seeing the links coming little downwards, can you please check this again?
<img width="1371" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/45e243ed-b396-4d94-883e-6ad12cefefe9">

2023-09-21 23:31 UTC, ravkiran requested changes
Please check the pdf output from the above comment

2023-09-22 03:11 UTC, jjjaspher commented
> @jjjaspher I'm still seeing the links coming little downwards, can you please check this again? <img alt="image" width="1371" src="https://user-images.githubusercontent.com/1553152/269780482-45e243ed-b396-4d94-883e-6ad12cefefe9.png">

Hi @ravkiran , I intentionally revert it to the original state because the code I deployed previously is not the right solution (convert links to text).

Expected: Upon generation of PDF links must be retain (clickable)

Actual: PDF links are not clickable and aligned downwards

I'm planning to revert it to original state then look for another solution.

2023-09-22 14:23 UTC, ravkiran approved these changes

2023-09-22 14:23 UTC, merged