96065 - filter date placeholder fix
hlxsites/accenture-newsroom pull request #293
Opened 2023-10-10 10:01 UTC by raymond-h-dev

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #158 

Test URLs:
- Before: https://main--accenture-newsroom--hlxsites.hlx.page/
- After: https://96065-filter-date-placeholder--accenture-newsroom--hlxsites.hlx.live/

2023-10-11 16:02 UTC, ravkiran requested changes
@raymond-h-dev since the element is input text, even though you put the value as placeholder, user will still be able to edit it 
<img width="1545" alt="image" src="https://github.com/hlxsites/accenture-newsroom/assets/1553152/c8480442-41a2-40cf-8eab-93b2b3840b6e">

You may have to set read only and update programmatically when the user selects the dates

2023-10-12 02:09 UTC, raymond-h-dev commented
> @raymond-h-dev since the element is input text, even though you put the value as placeholder, user will still be able to edit it <img alt="image" width="1545" src="https://user-images.githubusercontent.com/1553152/274342681-c8480442-41a2-40cf-8eab-93b2b3840b6e.png">
> 
> You may have to set read only and update programmatically when the user selects the dates

@ravkiran  good point, however we just need to follow what's in the live site right now. 

what we can do after we merge the code is ask for business approval from business team for your suggested enhancement, then create/log ticket for this and update this or create a new github issue.

2023-10-12 02:11 UTC, raymond-h-dev commented
@zozo-j  let's get business approval for @ravkiran  suggested enhancement

2023-10-12 20:55 UTC, ravkiran approved these changes

2023-10-12 20:55 UTC, merged